version: '3.9'
networks:
  internal:
services:
  mysql:
    container_name: mysql
    image: mysql:8.2.0
    environment:
      MYSQL_DATABASE: 'account_db'
      MYSQL_USER: 'admin'
      MYSQL_PASSWORD: 'teste@123'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
    networks:
     - internal
  app:
    container_name: app
    depends_on:
      - mysql
    build:
      context: ../
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - internal
    environment:
      - spring.datasource.url=jdbc:mysql://mysql:3306/account_db?allowPublicKeyRetrieval=true